### PR TITLE
Pin jupyter_client <7.0.0

### LINKED ISSUE #1511: jupyter console broken on latest conda-forge. Regression from jupyter_client-7.0.2
Regression against `jupyter_console-6.4.0` and ` jupyter_client-7.0.2 ` first reported in https://github.com/jupyter/jupyter_console/issues/251

### PR DESCRIPTION
**Pull request by davidbrochart**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Closes https://github.com/conda-forge/conda-forge.github.io/issues/1511, https://github.com/jupyter/jupyter_console/issues/251, https://github.com/jupyter/jupyter_client/issues/690.
Will need to unpin `jupyter_client` when https://github.com/jupyter/jupyter_console/pull/244 is merged.

@conda-forge-admin, please rerender

### CODE REVIEW

**Review by blink1073 — APPROVED** [review]
Thanks!

**Comment by jakirkham** [comment]
@davidbrochart, did you submit a repodata hot-fix as well?

**Comment by davidbrochart** [comment]
No, what is it?

**Comment by jakirkham** [comment]
It's how we [patch old packages]( https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/tree/master/recipe#readme ) to ensure they have the right version constraints (if that should change due to a new release of a dependency)

**Pull request merged**
