### PR TITLE
update to version 5.2.0

### PR DESCRIPTION
**Pull request by jjhelmus**
change source to PyPI
add version requirements to prompt_toolkit

### CODE REVIEW

**Comment by jjhelmus** [comment]
@conda-forge-admin, please rerender

**Comment by jakirkham** [comment]
Hmm...seems like we lost Travis CI. 😕

**Comment by minrk** [comment]
Travis shows the build rejected due to potential abuse:

screen shot 2017-10-13 at 10 28 44

I'm guessing too many conda-forge builds at once?

**Comment by ocefpaf** [comment]
Ouch! Never saw that message before :-(
Let's get this merged to cash the Win and Linux packages. And I'll keep an eye for OS X on master.

**Comment by jakirkham** [comment]
Would you mind raising an issue about this on [Travis CI's issue tracker]( https://github.com/travis-ci/travis-ci/issues ), @minrk? Feel free to cc me on the issue if you would like.

**Comment by jjhelmus** [comment]
@ocefpaf and I tracked the TravisCI issue down over the weekend.  

The issue is that Travis CI does not build PR coming from the `berryconda` organization.  I have no problems submitting from `jjhelmus` so I do not think there is an ongoing issue here.  I'm guessing that if I authenticated Travis CI on the `berryconda` organization I might be able to submit PR from there as well.

**Comment by jakirkham** [comment]
Thanks for the info Jonathan.

Probably Travis CI is unable to get a GitHub token since you haven't authenticated the `berryconda` org. This issue wouldn't necessarily extend to the other CIs as AppVeyor uses one of our bots for this purpose. CircleCI uses an SSH checkout key that we assign and I'm guessing your user to get a GitHub token (for updating the commit status and the like).

**Comment by jakirkham** [comment]
I'm not sure that is all this is. Recently had the same thing happen to me on the `notebook-feedstock`.

screen shot 2017-10-16 at 19 34 10

**Comment by jakirkham** [comment]
Based on the advice I have seen online, the recommendation is to email Travis CI directly. Have done so myself and would recommend others experiencing this issue do the same.

**Pull request merged**
